name: jafjaf
description: ''
version: '123'
author: kishore@simpledatalabs.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/new_job:
    name: new_job
    description: ''
    fabricUID: 30
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/test
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-05-26 14:55:10'
    author: vaibhav+1@prophecy.io
    models: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-04-12 15:34:56'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/CustomerOrders:
    name: CustomerOrders
    schema:
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: revenue
        dataType:
          type: Double
    description: null
    author: nathan@prophecy.io
    files:
    - models/CustomerOrders.sql
    - .prophecy/ide/models/CustomerOrders.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-08-02 18:29:07'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
      - name: credit_card_amount
        dataType:
          type: Double
      - name: coupon_amount
        dataType:
          type: Double
      - name: bank_transfer_amount
        dataType:
          type: Double
      - name: gift_card_amount
        dataType:
          type: Double
      - name: amount
        dataType:
          type: Double
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: maciej@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: first_order
        dataType:
          type: Date
      - name: most_recent_order
        dataType:
          type: Date
      - name: total_orders
        dataType:
          type: Bigint
      - name: customer_lifetime_value
        dataType:
          type: Double
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: maciej@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      providerType: Databricks
      fields:
      - name: payment_id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Double
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-04-12 15:35:01'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2023-04-12 15:35:01'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: maciej@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2023-04-12 15:35:01'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: kishore@simpledatalabs.com
  author: kishore@simpledatalabs.com
  createdAt: '2022-12-09 05:43:56'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
